### ISSUE TITLE
Uppercase A has white gaps

### ISSUE THREAD

**Issue by ancestral** [Etcetera-Type-Co/Anybody#2]
When I downloaded the beta, I noticed the uppercase A seems to have white gaps.

It’s present on every compiled version in the download.

<img width="45" alt="Screen Shot 2020-07-28 at 2 44 42 PM" src="https://user-images.githubusercontent.com/735024/88713456-f337e600-d0e0-11ea-9fbe-7e812c81d8d2.png">

**Comment by sursly** [comment]
Hey @ancestral are you on a windows computer? Give me some examples of your setup. What version of the font are you using? Where (application?) are you using it?

**Comment by ancestral** [comment]
I’m on a Mac, running Catalina, 10.15.6. I downloaded the entire project, and every otf and ttf in those directories looks like this in Font Book, and any app after it’s installed onto the system.

**Comment by sursly** [comment]
Ah, yes, I see that was resolved with a more recent commit that never made it to the "releases" - I'll make a new release, but the latest version of Anybody has resolved this.

**Comment by sursly** [comment]
Here's the update: https://github.com/Etcetera-Type-Co/Anybody/archive/BetaBetter.zip
